### ISSUE TITLE
Readme vs Reality

### ISSUE THREAD

**Issue by judemont** [SavrinAlif/Todo-App#2]
Readme :star_struck: :star_struck: : 
![image](https://github.com/SavrinAlif/Todo-App/assets/96385330/fadec800-f437-426b-9a07-9cdb47e33f7d)
REALITY 😳😳:

![image](https://github.com/SavrinAlif/Todo-App/assets/96385330/d38ce71b-3e4a-400e-9f99-a662d18b36dd)

**Comment by savrin-sharif** [comment]
Now Readme == Reality
